In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

In [2]:
df = pd.read_csv("LArealestate.csv")

In [3]:
#df.isna().sum()/df.shape[0]*100

df.dropna(inplace = True)

In [4]:
df["agency"] = df.date.apply(lambda x : x[10:])
df["date"] = df.date.apply(lambda x : x[:10])

In [5]:
df["street"] = df.address.apply(lambda x : " ".join(x.strip().split(" ")[1:]))
df["postal_code"] = df.address.apply(lambda x : (x.strip().split(" ")[0]))

df.drop("address", axis = 1, inplace = True)

In [6]:
df["year"] = df.date.apply(lambda x : x.split("/")[-1])
df["month"] = df.date.apply(lambda x : x.split("/")[1])
df["day"] = df.date.apply(lambda x : x.split("/")[0])

df.drop("date", axis = 1, inplace = True)

In [8]:
df.beds.unique()

array([ 8.,  2.,  4.,  5.,  3.,  7.,  6.,  1.,  9., 10.])

In [9]:
df

,beds,baths,sqft,price,city,type,agency,street,postal_code,year,month,day
0,8.0,11.0,10379.0,18000000.0,Beverly Hills,sfh,Hilton & HylandFeatured,Benedict Canyon Dr,1005,2014,08,03
1,2.0,3.0,2013.0,950000.0,Beverly Hills,sfh,Coldwell Banker Residential Brokerage - Sherma...,Westwanda Dr,10084,2013,11,12
2,4.0,5.0,3476.0,9750000.0,Beverly Hills,sfh,Hilton & Hyland,N Beverly Dr,1009,2014,18,03
3,5.0,6.5,7718.0,16500000.0,Beverly Hills,sfh,John Aaroe Group,N Rexford Dr,1010,2014,01,03
4,3.0,1.5,4000.0,24250000.0,Beverly Hills,sfh,Rodeo Realty Inc.,Angelo View Dr,10101,2014,24,03
...,...,...,...,...,...,...,...,...,...,...,...,...
250,1.0,1.0,676.0,299000.0,Palms,condo,The Agency,Cardiff Ave Apt 201,3640,2014,25,03
251,2.0,3.0,1419.0,524000.0,Palms,condo,Coldwell Banker Residential Brokerage - Santa ...,Glendon Ave Apt 9,3701,2014,24,03
252,1.0,1.0,692.0,349000.0,Palms,condo,Rodeo Realty Inc.,National Blvd Apt 101,9313,2014,24,03
253,2.0,2.0,824.0,399000.0,Palms,condo,Keller WilliamsFeatured,National Blvd Apt 203,9313,2014,18,03
254,2.0,2.0,1224.0,399000.0,Palms,condo,Keller Williams Realty Santa MonicaFeatured,S Sepulveda Blvd Apt G9,3300,2014,24,03